version: '3.9'
volumes:
  mariadb_data: {}
  mongodb_data: {}
networks:
  espo-network:
    driver: bridge

services:
  mariadb:
    container_name: espo_mariadb
    image: mariadb:10.7.4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: espo_phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1

  redis:
    container_name: espo_redis
    image: redis
    restart: always
    volumes:
      - ./images/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  redisinsight:
    container_name: espo_redisinsight
    image: redislabs/redisinsight
    restart: always

  mongo:
    container_name: espo_mongo
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    container_name: espo_mongo_express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  load_balancer:
    container_name: espo_lb
    image: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${PWD}/configs/load_balancer/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/configs/load_balancer/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/configs/load_balancer/conf.d/phpmyadmin:/etc/nginx/conf.d/phpmyadmin
      - ${PWD}/configs/load_balancer/conf.d/mongo_express:/etc/nginx/conf.d/mongo_express
      - ${PWD}/configs/load_balancer/conf.d/ssl:/etc/nginx/conf.d/ssl
      - ${PWD}/configs/load_balancer/conf.d/espo:/etc/nginx/conf.d/espo
      - ${PWD}/configs/load_balancer/conf.d/redisinsight:/etc/nginx/conf.d/redisinsight
      - ${PWD}/configs/ssls/dhparam.pem:/etc/nginx/conf.d/dhparam.pem
      - ${PWD}/configs/ssls/ssl.crt:/etc/nginx/conf.d/ssl.crt
      - ${PWD}/configs/ssls/ssl.key:/etc/nginx/conf.d/ssl.key
    networks:
      default:
      espo-network:
    depends_on:
      - espo1
      - espo2
      - espo3
      - espo4

  espo1:
    container_name: espo1
    restart: always
    build:
      context: ./images/ubuntu20-php81
    volumes:
      - ${ESPO_PROJECT_PATH}:/var/www
      - ${PWD}/logs/espo1:/home
      - ${PWD}/configs/servers/espo.conf:/etc/nginx/sites-enabled/default
      - ${PWD}/configs/servers/espo1/server_config:/etc/nginx/conf.d/server_config
      - ${PWD}/configs/servers/espo1/server_name:/etc/nginx/conf.d/server_name
    networks:
      default:
      espo-network:

  espo2:
    container_name: espo2
    restart: always
    build:
      context: ./images/ubuntu20-php81
    volumes:
      - ${ESPO_PROJECT_PATH}:/var/www
      - ${PWD}/logs/espo2:/home
      - ${PWD}/configs/servers/espo.conf:/etc/nginx/sites-enabled/default
      - ${PWD}/configs/servers/espo2/server_config:/etc/nginx/conf.d/server_config
      - ${PWD}/configs/servers/espo2/server_name:/etc/nginx/conf.d/server_name
    networks:
      default:
      espo-network:

  espo3:
    container_name: espo3
    restart: always
    build:
      context: ./images/ubuntu20-php81
    volumes:
      - ${ESPO_PROJECT_PATH}:/var/www
      - ${PWD}/logs/espo3:/home
      - ${PWD}/configs/servers/espo.conf:/etc/nginx/sites-enabled/default
      - ${PWD}/configs/servers/espo3/server_config:/etc/nginx/conf.d/server_config
      - ${PWD}/configs/servers/espo3/server_name:/etc/nginx/conf.d/server_name
    networks:
      default:
      espo-network:

  espo4:
    container_name: espo4
    restart: always
    build:
      context: ./images/ubuntu20-php81
    volumes:
      - ${ESPO_PROJECT_PATH}:/var/www
      - ${PWD}/logs/espo4:/home
      - ${PWD}/configs/servers/espo.conf:/etc/nginx/sites-enabled/default
      - ${PWD}/configs/servers/espo4/server_config:/etc/nginx/conf.d/server_config
      - ${PWD}/configs/servers/espo4/server_name:/etc/nginx/conf.d/server_name
    networks:
      default:
      espo-network: